export const NEWS_DATA = [
    {
        id: 1,
        title: 'Performance Testing: What It Is and Why It Matters',
        excerpt: 'A software system is judged not only by what it can do, but by how fast, how stable, and how well it performs under pressure.',
        content: `
      <p>Performance testing is a non-functional software testing technique that determines how the stability, speed, scalability, and responsiveness of an application holds up under a given workload. It's a key step in ensuring software quality, but unfortunately, is often seen as an afterthought, in isolation, and to begin once functional testing is over, and in most cases, after the code is ready to release.</p>
      
      <h3>Why is Performance Testing Important?</h3>
      <p>Performance testing is critical for customer satisfaction. If your application is slow, users will leave. If it crashes, they may never come back. Performance testing helps you identify bottlenecks and fix them before they impact your users.</p>
      
      <h3>Types of Performance Testing</h3>
      <ul>
        <li><strong>Load Testing:</strong> Checks the application's ability to perform under anticipated user loads. The objective is to identify performance bottlenecks before the software application goes live.</li>
        <li><strong>Stress Testing:</strong> Involves testing an application under extreme workloads to see how it handles high traffic or data processing. The objective is to identify the breaking point of an application.</li>
        <li><strong>Endurance Testing:</strong> Is done to make sure the software can handle the expected load over a long period of time.</li>
        <li><strong>Spike Testing:</strong> Tests the software's reaction to sudden large spikes in the load generated by users.</li>
      </ul>
    `,
        date: 'November 25, 2025',
        category: 'BLOGS',
        author: 'Ms Chau Anh',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    },
    {
        id: 2,
        title: 'What is a playwright? The Powerful Assistant for Automation Testers',
        excerpt: 'Playwright doesn\'t just automate browser actions. It automates the modern testing mindset: faster, more accurate, and more reliable.',
        content: `
      <p>Playwright is a Node.js library to automate Chromium, Firefox and WebKit with a single API. It is built to enable cross-browser web automation that is ever-green, capable, reliable and fast.</p>
      
      <h3>Key Features</h3>
      <p>Playwright was built specifically for the modern web. It supports all modern rendering engines including Chromium, WebKit, and Firefox. It can test on Windows, Linux, and macOS, locally or on CI, headless or headed.</p>
      
      <h3>Why Choose Playwright?</h3>
      <p>Playwright delivers reliable end-to-end testing for modern web apps. It provides a unified API to automate all major browsers, and its powerful selectors and auto-waiting mechanisms make tests more stable and less flaky.</p>
    `,
        date: 'November 18, 2025',
        category: 'BLOGS',
        author: 'Ms Chau Anh',
        image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    },
    {
        id: 3,
        title: 'From Tester to Quality Assurance: The Mindset Shift',
        excerpt: 'Moving from finding bugs to preventing them is the key evolution in a QA\'s career path. Learn how to make this transition effectively.',
        content: `
      <p>The transition from a Tester to a Quality Assurance (QA) professional involves a significant shift in mindset. While testing focuses on finding bugs, QA focuses on preventing them. It's about ensuring quality throughout the entire software development lifecycle.</p>
      
      <h3>The Tester Mindset</h3>
      <p>Testers typically focus on executing test cases and finding defects. They ask "Does this work as expected?" and "Can I break this?".</p>
      
      <h3>The QA Mindset</h3>
      <p>QA professionals look at the bigger picture. They ask "Are we building the right thing?", "Is the process efficient?", and "How can we improve quality from the start?". They are involved in requirements analysis, design reviews, and process improvement.</p>
    `,
        date: 'November 7, 2025',
        category: 'CAREER',
        author: 'Mr Tuan Stark',
        image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    },
    {
        id: 4,
        title: 'The Story of Devs and Testers in SCRUM',
        excerpt: 'Collaboration between developers and testers is crucial for SCRUM success. Here are some best practices for better teamwork.',
        content: `
      <p>In Agile SCRUM, developers and testers are part of the same team, working towards a common goal. However, friction can sometimes arise. Effective collaboration is key to delivering high-quality software at speed.</p>
      
      <h3>Breaking Down Silos</h3>
      <p>Traditionally, developers and testers worked in separate silos. In SCRUM, they must work together daily. This requires open communication, mutual respect, and a shared understanding of quality.</p>
      
      <h3>Best Practices</h3>
      <ul>
        <li><strong>Shift Left:</strong> Involve testers early in the process, during requirements refinement and planning.</li>
        <li><strong>Pair Programming/Testing:</strong> Developers and testers can pair up to write code or tests, sharing knowledge and catching issues early.</li>
        <li><strong>Continuous Feedback:</strong> Provide feedback quickly and constructively.</li>
      </ul>
    `,
        date: 'October 25, 2025',
        category: 'AGILE',
        author: 'Team Lead',
        image: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    }
]
