export { default as HeroSection } from './HeroSection'
export { default as FeaturedDormsSection } from './FeaturedDormsSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as AmenitiesSection } from './AmenitiesSection'
export { default as CTASection } from './CTASection'
export { default as PartnersSection } from './PartnersSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as NewsSection } from './NewsSection'
